### PR TITLE
Update container image paths to point to `ceph` instead of `prometheus`

### PR DESCRIPTION
**Pull request by p-se**
Signed-off-by: Patrick Seidensal <pseidensal@suse.com>

### CODE REVIEW

**Comment by p-se** [comment]
As updating just the path to the container images is not possible, because the container images would be built with the newest available version, the update of both, the container image paths for Ceph as well as the docs update are postponed until updates to the container images are released which actually use the new container images.

**Review by tbazant — COMMENTED** [review]
LGTM

**Comment by p-se** [comment]
Files already [up-to-date](https://github.com/SUSE/ceph/commit/dfe2b2888bd914ae433099edffc41da0044fe305).

**Review by tbazant — APPROVED** [review]
LG

**Review by ml8mr — APPROVED** [review]
LGTM

**Pull request merged**
