### PR TITLE
Convert RST Manpages into DocBook

### PR DESCRIPTION
**Pull request by tomschr**
This PR contains the following changes:

* a `convert-manpages.sh` script which downloads and converts all the RST files into DocBook.  Does the following steps:

   1. Check if all necessary programs are installed. If not, show help text.
   2. Clone the repository (or use the directory from last run).
   3. Download additional manpages.
   4. Remove any `:orphan:` lines from RST (this simplifies the conversion process).
   5. Convert RST to DocBook5 with pandoc.
   6. Fix the raw XML file from pandoc, write it to result directory.

* a `xslt/fix-manpages.xsl` XSLT stylesheets which corrects issues from the pandoc conversion

### CODE REVIEW

**Review by asettle — APPROVED** [review]

**Comment by asettle** [comment]
@tomschr this looks fantastic and easy to implement. I guess I need to create a DC file, and a book_storage_man.xml file? Are there specific tags (such as `<appendix>`) to create the man-page specific book? Or just `<chapter>`?

Also, is it possible to change the formatting that the script runs? For example, in the XML files it provides `<section>`, whereas we usually use `<sect1>` etc

**Comment by tomschr** [comment]
Thank you. :-) So the basic idea is to do the conversion once, move some files into `xml/` and integrate them into a book. If upstream changes, rerun the script.

> I guess I need to create a DC file, and a book_storage_man.xml file? 

That depends if you want to create a completely separate book or if you want to integrate the manpages into an existing one.


> Are there specific tags (such as <appendix>) to create the man-page specific book? Or just <chapter>?

This is one part that I would like to get your input.
Normally, with DocBook you would use the tags `<reference>` and `<refentry>`. However, you can do similar things with other structures like `<article>` or `<book>` and `<section>`s. It's a bit a matter of taste and if you want to generate manpages from your XML sources (probably the latter is not an issue).

For example, if we start with `<article>` for all manpages, we could just xinclude them in your article main file. That gives you the opportunity to either render it as a completely separate guide or integrate it into a larger book structure.


> Also, is it possible to change the formatting that the script runs? For example, in the XML files it provides <section>, whereas we usually use <sect1> etc

Sure! I need to change the stylesheet.

**Comment by tomschr** [comment]
@asettle With the last commit 27d1a70 you have `sectX` elements throughout your XML files. As all root elements are now `sect1`s, your article looks like this:

```xml
<article version="5.1
   http://docbook.org/ns/docbook xmlns:xi="http://www.w3.org/2001/XInclude">
   <title>Manpages</title>
   <info>
     <!-- add authors etc. here -->
   </info>
  <xi:include href="first.xml"/>
  <xi:include href="second.xml"/>
  <!-- add more files here -->
</article>
```

**Comment by tomschr** [comment]
I forget to add one thing:
With `<article>`, all the `<sect1>` render as a consecutive flow of text in PDF. There are no page breaks between `<sect1>`s. This may or may not what you want.

If you prefer page breaks between each `<sect1>`, you could try to add the processing instruction `<?pdfpagebreak?>` like this:

```xml
<article version="5.1 xml:id="art-storage-man"
   http://docbook.org/ns/docbook xmlns:xi="http://www.w3.org/2001/XInclude">
   <title>Manpages</title>
   <info>
     <!-- add authors etc. here -->
   </info>
  <xi:include href="first.xml"/>
  <?pdfpagebreak?>
  <xi:include href="second.xml"/>
  <?pdfpagebreak?>
  <!-- add more files here -->
</article>
```

I'm not entirely sure if this really works, but the FO stylesheets have a rule for that and it should work.

**Comment by asettle** [comment]
@tomschr - okay, so I've created my article using your instructions. Already stumbled onto a problem: The file generates generic XML IDs for each section, and most of them are duplicated.

For example:

```asettle@linux-nrkp:~/susedoc/doc-ses> daps -d DC-ses-man validate
ERROR: Element 'article' doesn't contain attribute lang!
no result for /home/asettle/susedoc/doc-ses/xml/art-storage-man.xml
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ganesha-rgw-config.xml:8:28: error: ID "synopsis" has already been defined
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ceph-volume.xml:7:28: error: first occurrence of ID "synopsis"
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ganesha-rgw-config.xml:17:31: error: ID "description" has already been defined
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ceph-volume.xml:24:31: error: first occurrence of ID "description"
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ganesha-rgw-config.xml:125:28: error: ID "see-also" has already been defined
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ceph-volume.xml:654:28: error: first occurrence of ID "see-also"
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ganesha-rados-grace.xml:5:28: error: ID "synopsis" has already been defined
```

So it's going to fail every time. What do you suggest?

**Comment by tomschr** [comment]
@asettle I think, I've fixed the ID issue. Now, the script takes the filename into account. This ensures that the ID is unique. There is only one disadvantage to this approach: the ID values get quite long.

For example, this is the ID before:

```xml
<section xml:id="synopsis">
    <title>SYNOPSIS</title>
``` 

after the ID correction it is this:

```xml
<sect2 xml:id="man-ganesha-9p-config-synopsis">
    <title>SYNOPSIS</title>
``` 

As you can see, there is a prefix (`man-`). You can change that if you wish as the script now supports the new option `-i`/`--idprefix`.

**Comment by asettle** [comment]
Oof, we're still getting tonnes of errors for the entity names. I'm going to push up my book, and see if you can take a look @tomschr (do you have time?)

Here's some of the output:

```
asettle@linux-nrkp:~/susedoc/doc-ses> daps -d DC-ses-man validate
warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ceph-volume.xml"
warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-rgw-config.xml"
warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-rados-grace.xml"
warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-rados-cluster-design.xml"
warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-log-config.xml"
warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-export-config.xml"
warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-core-config.xml"
warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-config.xml"
warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-ceph-config.xml"
warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-cache-config.xml"
```

**Comment by asettle** [comment]
> Oof, we're still getting tonnes of errors for the entity names. I'm going to push up my book, and see if you can take a look @tomschr (do you have time?)
> 
> Here's some of the output:
> 
> ```
> asettle@linux-nrkp:~/susedoc/doc-ses> daps -d DC-ses-man validate
> warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ceph-volume.xml"
> warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-rgw-config.xml"
> warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-rados-grace.xml"
> warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-rados-cluster-design.xml"
> warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-log-config.xml"
> warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-export-config.xml"
> warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-core-config.xml"
> warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-config.xml"
> warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-ceph-config.xml"
> warning: failed to load external entity "/home/asettle/susedoc/doc-ses/xml/ganesha-cache-config.xml"
> ```

Ugh, I know why these aren't loading. I seem to have accidentally removed the manpages directory instead of copying. Hang on.

**Comment by asettle** [comment]
Lovely, now we're back to the ID ref errors:

```asettle@linux-nrkp:~/susedoc/doc-ses> daps -d DC-ses-man validate
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ganesha-rgw-config.xml:8:30: error: ID "synopsis" has already been defined
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ceph-volume.xml:7:30: error: first occurrence of ID "synopsis"
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ganesha-rgw-config.xml:17:33: error: ID "description" has already been defined
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ceph-volume.xml:24:33: error: first occurrence of ID "description"
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ganesha-rgw-config.xml:125:30: error: ID "see-also" has already been defined
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ceph-volume.xml:654:30: error: first occurrence of ID "see-also"
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ganesha-rados-grace.xml:5:30: error: ID "synopsis" has already been defined
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ceph-volume.xml:7:30: error: first occurrence of ID "synopsis"
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ganesha-rados-grace.xml:13:33: error: ID "description" has already been defined
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ceph-volume.xml:24:33: error: first occurrence of ID "description"
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ganesha-rados-grace.xml:80:30: error: ID "commands" has already been defined
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ceph-volume.xml:40:30: error: first occurrence of ID "commands"
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ganesha-log-config.xml:8:30: error: ID "synopsis" has already been defined
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ceph-volume.xml:7:30: error: first occurrence of ID "synopsis"
/home/asettle/susedoc/doc-ses/build/.profiled/noprofile/ganesha-log-config.xml:14:33: error: ID "description" has already been defined
```

**Comment by asettle** [comment]
I'm going to restart this process, because all my manpages are old and don't have the new ID refs :+1:

**Comment by asettle** [comment]
HOORAY it builds! :partying_face: it looks good to me, @tomschr

**Pull request merged**
