### PR TITLE
Minor changes to the the current registry deployment

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

This is a temporary mitigation, till https://jira.suse.com/browse/SES-2304 provides a better overall solution

### CODE REVIEW

**Review by lproven — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
dnm, till ricardo approves

**Review by ricardoasmarques — APPROVED** [review]
since it's temporary, lgtm

**Comment by asettle** [comment]
@sebastian-philipp I will put a timer on this fix. The actual technical solution needs to be in place. Let's discuss an appropriate timeframe before I revert this PR.

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp I will put a timer on this fix. The actual technical solution needs to be in place. Let's discuss an appropriate timeframe before I revert this PR.

simply **reverting** this PR will be bad, but yes I agree about making sure this is temporary.

**Comment by asettle** [comment]
> > @sebastian-philipp I will put a timer on this fix. The actual technical solution needs to be in place. Let's discuss an appropriate timeframe before I revert this PR.
> 
> simply **reverting** this PR will be bad, but yes I agree about making sure this is temporary.

I've commented in the BZ. Sure, we won't revert - just a turn of phrase to say I will remove this change after a certain period of time. 

Please provide a timeline in the BZ and I'll ensure we are covered on this end :)

**Comment by sebastian-philipp** [comment]
Sorry, I can't give you a timeline.

**Comment by asettle** [comment]
> Sorry, I can't give you a timeline.

Then you must provide a timeline by which you will check in with an appropriate response. I will not merge something that is largely ill-advised and not an official part of the procedure.

**Comment by asettle** [comment]
Closing - replaced by #825

**Pull request closed without merging**
