### PR TITLE
Updating logging commands (BSC#1174631)

### PR DESCRIPTION
**Pull request by asettle**

### CODE REVIEW

**Comment by asettle** [comment]
Screenshot from 2020-10-21 15-58-15
Screenshot output

**Comment by smithfarm** [comment]
Regarding section "3.2 Checking cephadm Logs": I'm confused by the words "If you have enabled logging to files"... how does one "enable logging to files"?

Regarding "3.3 Gathering Log Files" I have a couple gripes:

1. The title of the section doesn't sound right. How about "Accessing Ceph Daemon Logs"?
2. In an actual SES7 cluster, I've found that the procedure for accessing daemon logs is actually much simpler than is being presented here. The procedure is:

a. using `ceph orch ps` (or `ceph orch ps <node_name>` or `ceph orch ps --daemon-type <daemon_type>`) find the "cephadm name" of the daemon in question and the host where it is running. For example, if I want to look at the prometheus log, I would do:

```
master:~ # ceph orch ps --daemon-type prometheus
NAME               HOST    STATUS         REFRESHED  AGE  VERSION  IMAGE NAME                                             IMAGE ID      CONTAINER ID  
prometheus.master  master  running (65m)  7m ago     2h   2.18.0   registry.suse.com/caasp/v4.5/prometheus-server:2.18.0  e77db6e75e78  7b11062150ab  
```

and find that the name is "prometheus.master" and the host is "master"

b. ssh to the host where the daemon is running

c. `cephadm logs --name <cephadm_name_of_daemon>`

That's all. We don't need to discuss `journalctl -u`. We can also omit the bash snippet for dumping all the cephadm daemon logs into files - that's already automated by supportconfig.

**Comment by asettle** [comment]
> Regarding section "3.2 Checking cephadm Logs": I'm confused by the words "If you have enabled logging to files"... how does one "enable logging to files"?

I think I'll remove this. It's an upstream addition that, frankly, makes no sense. Even if you follow the procedure upstream.

> 
> Regarding "3.3 Gathering Log Files" I have a couple gripes:
> 
> 1. The title of the section doesn't sound right. How about "Accessing Ceph Daemon Logs"?

Sounds good.

> 2. In an actual SES7 cluster, I've found that the procedure for accessing daemon logs is actually much simpler than is being presented here. The procedure is:
> 
> a. using `ceph orch ps` (or `ceph orch ps <node_name>` or `ceph orch ps --daemon-type <daemon_type>`) find the "cephadm name" of the daemon in question and the host where it is running. For example, if I want to look at the prometheus log, I would do:
> 
> ```
> master:~ # ceph orch ps --daemon-type prometheus
> NAME               HOST    STATUS         REFRESHED  AGE  VERSION  IMAGE NAME                                             IMAGE ID      CONTAINER ID  
> prometheus.master  master  running (65m)  7m ago     2h   2.18.0   registry.suse.com/caasp/v4.5/prometheus-server:2.18.0  e77db6e75e78  7b11062150ab  
> ```
> 
> and find that the name is "prometheus.master" and the host is "master"
> 
> b. ssh to the host where the daemon is running
> 
> c. `cephadm logs --name <cephadm_name_of_daemon>`
> 
> That's all. We don't need to discuss `journalctl -u`. We can also omit the bash snippet for dumping all the cephadm daemon logs into files - that's already automated by supportconfig.

@jschmid1 thoughts? I leave this to you two.

**Comment by jschmid1** [comment]
@asettle @smithfarm Sounds good to me. Lets go with these suggestsions

**Comment by asettle** [comment]
Screenshot from 2020-10-21 17-08-51
Better Version :tm:

**Comment by asettle** [comment]
Happy to also transform this into a numbered procedure, as I think it would read better. But for now, this is the details.

**Comment by smithfarm** [comment]
@asettle 

A couple more nits:

1. in the title of section "3.2 Checking cephadm logs", shouldn't "logs" be "Logs"? (I had the feeling that U.S. usage is more-or-less being used)

2. This part is an "aside":

```
For example, if I want to look at the prometheus log, I would do:

master:~ # ceph orch ps --daemon-type prometheus
NAME               HOST    STATUS         REFRESHED  AGE  VERSION  IMAGE NAME                                             IMAGE ID      CONTAINER ID  
prometheus.master  master  running (65m)  7m ago     2h   2.18.0   registry.suse.com/caasp/v4.5/prometheus-server:2.18.0  e77db6e75e78  7b11062150ab  

and find that the name is "prometheus.master" and the host is "master"
```

Would it help to put it in some kind of box?

3. since it's not a numbered list (and I actually prefer having paragraphs of text instead of bullets and lists), could we merge "ssh to the host where the daemon is running" and "to view the daemon's logs, execute the following" like so:

```
To view the daemon's logs, execute the following on the host where the daemon is running:
```

4. (and again, consider putting the "For example" thingy in a box)

I think having the examples in boxes would make the simplicity of this procedure really stand out.

**Review by smithfarm — APPROVED** [review]

**Review by lproven — APPROVED** [review]

**Pull request merged**
