### PR TITLE
Fixed PTF process (bsc#1193293)

### PR DESCRIPTION
**Pull request by tbazant**
closes bsc#1193293

rendered PDF is attached 
[bp-troubleshooting-cephadm_color_en.pdf](https://github.com/SUSE/doc-ses/files/7668494/bp-troubleshooting-cephadm_color_en.pdf)

### CODE REVIEW

**Review by asettle — APPROVED** [review]
Thanks!

**Review by lezare — COMMENTED** [review]
Since a PTF may be related to other services, should we not also add a note on how to get the relevant mon key for the service in question? I am referring to this part from the bug description:

Determine the mon key corresponding to the desired service(s):
    # ceph auth ls | grep [DAEMON_TYPE]

**Comment by tbazant** [comment]
> Since a PTF may be related to other services, should we not also add a note on how to get the relevant mon key for the service in question? I am referring to this part from the bug description:
> 
> Determine the mon key corresponding to the desired service(s): # ceph auth ls | grep [DAEMON_TYPE]

@lezare One procedure step added, please check

**Review by lezare — APPROVED** [review]
LGTM.

**Pull request merged**
