### PR TITLE
Added 1 step to OSD 6 > 7.1 upgrade procedure for format conversion

### PR DESCRIPTION
**Pull request by tbazant**
closes #1003 

PDF is attached
[upgrade-mon-mgr-nodes_color_en.pdf](https://github.com/SUSE/doc-ses/files/8322857/upgrade-mon-mgr-nodes_color_en.pdf)

### CODE REVIEW

**Review by tserong — APPROVED** [review]
Thanks, I think this is by far the most straightforward way to do this procedure given the options I outlined in #1004 :-)

@mgfritch, what do you think? Do we need to add any information about those other possible ways of doing this thing?

**Review by asettle — COMMENTED** [review]
One nit

**Review by mgfritch — APPROVED** [review]
> @mgfritch, what do you think? Do we need to add any information about those other possible ways of doing this thing?

this seems like the best approach, it anything maybe a note to perform the adoption on a per OSD or per node basis ... ?

**Comment by tserong** [comment]
> this seems like the best approach, it anything maybe a note to perform the adoption on a per OSD or per node basis ... ?

The docs already say at the start to "Upgrade the Ceph Monitor, Ceph Manager, and OSD nodes one at a time", so I think that covers the per-node basis. We don't actually have a means for DeepSea to do the adoption per OSD, for that you'd have to run `cephadm adopt` by hand.

**Review by dariavladykina — APPROVED** [review]
LGTM!

**Pull request merged**
