### PR TITLE
Copy-edit of new Rook guide

### PR DESCRIPTION
**Pull request by lproven**
I have gone through the entire chapter. Some important changes include missing/lost indentation in one section.

### CODE REVIEW

**Review by asettle — APPROVED** [review]
In a blind act of faith, I say LGTM without fully reading. Really appreciate your review!

**Comment by asettle** [comment]
Forward port to ses 6

**Comment by lproven** [comment]
> In a blind act of faith, I say LGTM without fully reading. Really appreciate your review!

Whoah. Thank you.

I think the biggie was that all the YAML in the Troubleshooting section had lost all indentation. AIUI that would leave it totally non-functional, and it is not trivial to re-insert it without seeing the original.

**Comment by asettle** [comment]
> > In a blind act of faith, I say LGTM without fully reading. Really appreciate your review!
> 
> Whoah. Thank you.
> 
> I think the biggie was that all the YAML in the Troubleshooting section had lost all indentation. AIUI that would leave it totally non-functional, and it is not trivial to re-insert it without seeing the original.

Thanks for the heads up. I'll go back through and re-indent anything that looks suspicious.

**Comment by lproven** [comment]
> Thanks for the heads up. I'll go back through and re-indent anything that looks suspicious.

I checked a few other sections, before and after. They looked OK. All I could see is that at least some are indented by 2 spaces _throughout_ -- in other words the margin starts at 2 spaces in. I am *not* a Python or YAML expert, but if I understand correctly, it's _relative_ indentation that matters and that what I describe should therefore work fine.

**Pull request merged**
