### PR TITLE
Fix xml:id/linkend handling

### PR DESCRIPTION
**Pull request by tomschr**
To make it SEO compatible, replace any "-" and other characters with underscore

### CODE REVIEW

**Review by tbazant — APPROVED** [review]
what i understand looks good, the rest is pure belief :-)

**Comment by tomschr** [comment]
Haha, okay. I've tested it with:

```
$ ./convert-manpages.sh -v manpages
```

That will clone the sources from an upstream repository, creates a temporary directory (e.g. `/tmp/nfs-ganesha-01yO2/`) and the result is saved in `manpages`. You can reuse the temp directory with the `-g` option, if you need to call the script again.

The GH Action still fails as I haven't committed the updated manpages into `xml`. I leave that up to you to check if it's safe to do so. :wink: Just ask if you need help.

Merge the PR whenever you think it's right.

**Review by tbazant — CHANGES_REQUESTED** [review]
the script replaces with underscores, but the point was to remove underscores from ID's and xrefs completely :-)

**Review by tbazant — APPROVED** [review]
LGTM

**Pull request merged**
